'use client'

// This file is auto-generated by generate-entries.js
// Do not edit manually - regenerate with: nxcode generate

import { ReactNode } from 'react'
import { AuthProvider } from '@/modules/auth/components/AuthProvider'

interface ProvidersProps {
  children: ReactNode
}

export function Providers({ children }: ProvidersProps) {
  return (
<AuthProvider>{children}</AuthProvider>
  )
}
